[package]
name = "display_simulator"
version = "1.20.0"
authors = ["Georg Brandl <g.brandl@fz-juelich.de>"]
description = "Simulator for MLZ control box display"
license = "GPL-2.0+"
edition = "2018"

[dependencies]
nix = "0.18"
minifb = { version = "0.19", default-features = false, features = ["x11"] }
structopt = "0.3.0"
crossbeam-channel = "0.4.0"
display = { path = "../lib" }

[features]
default = ["customer-mlz"]
customer-mlz = ["display/customer-mlz"]
customer-psi = ["display/customer-psi"]
