[package]
name = "display_simulator"
version = "0.1.0"
authors = ["Georg Brandl <g.brandl@fz-juelich.de>"]
description = "Simulator for MLZ control box display"
license = "GPL-2.0+"
edition = "2018"

[dependencies]
nix = "0.14.1"
minifb = "0.11.2"
structopt = "0.2.12"
crossbeam-channel = "0.3.8"
display = { path = "../lib" }
