[package]
name = "stm_display"
version = "0.0.1"
authors = ["Georg Brandl <g.brandl@fz-juelich.de>"]
description = "Demo display app..."
license = "GPL-2.0+"

[profile.release]
lto = true
codegen-units = 1
debug = true

[dependencies]
nb = "0.1"
heapless = { version = "0.4", features = ["const-fn", "smaller-atomics"] }
btoi = { version = "0.4", default-features = false }
bresenham = "0.1"
cortex-m = "0.5"
cortex-m-rt = "0.6"
cortex-m-semihosting = "0.3"
panic-semihosting = "0.5"
embedded-hal = "0.2"
stm32f429 = { git = "https://github.com/birkenfeld/stm32f429", features = ["rt"] }
stm32f429-hal = { git = "https://github.com/birkenfeld/stm32f429-hal", features = ["rt"] }
